[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_dapp = "9E3vbRyXQ5hXzoJTmDmg25jvDf2kx7MipnPQmGN59Qft"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
